version: '3'
services:
  mysqldb:
    image: mysql:5.7
    ports:
      - "127.0.0.1:3306:3306"
    command: "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_USER: wallet
      MYSQL_PASSWORD: walletpassword
      LANG: C.UTF-8
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-proot",  "ping", "-h", "127.0.0.1"]
      start_period: 60s
      timeout: 15s
      interval: 15s
      retries: 30

  wallet:
    build: ./
    links:
      - mysqldb
    depends_on:
      - mysqldb
    environment:
      spring.datasource.url: "jdbc:mysql://mysqldb:3306/wallet"
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.username: "wallet"
      spring.datasource.password: "walletpassword"
    expose:
      - "8080"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 2s
      retries: 3
      start_period: 60s
